[tool.black]
    line-length = 99
    target-version = ['py311']
    include = '\.pyi?$'

[tool.pyright]
    pythonVersion = '3.11.0'
    reportUnnecessaryTypeIgnoreComment = true

[tool.ruff]
    select = ['E', 'F', 'B', 'Q', 'I', 'W']
    ignore = ['E501']
    target-version = 'py311'
    line-length = 99

[tool.ruff.isort]
    combine-as-imports = true
    extra-standard-library = ['typing_extensions']
